/**
 * Mappings for RVO Codelists and Indicators.
 * Values derived from Berichtenboek EDI-Crop BS and Berichtenboek Regelingspercelen Mest.
 */

export const CODELISTS: Record<string, Record<string, string>> = {
  /** Use Title Codes (CL412) */
  UseTitleCode: {
    "01": "Eigendom",
    "02": "Reguliere pacht",
    "03": "In gebruik van een terreinbeherende organisatie",
    "04": "Tijdelijk gebruik Land-, Reconstructie- of Herinrichtingswet",
    "07": "Overige exploitatievormen",
    "09": "Erfpacht",
    "10": "Pacht van geringe oppervlakten",
    "11": "Natuurpacht (reservaats- of beheerspacht)",
    "12": "Geliberaliseerde pacht, langer dan 6 jaar",
    "13": "Geliberaliseerde pacht, 6 jaar of korter",
    "61": "Reguliere pacht kortlopend",
    "62": "Eenmalige pacht",
    "63": "Teeltpacht",
  },
  /** Ground Soil Types (CL405) */
  Grondsoort: {
    "1": "Grondsoort > 50% Klei",
    "2": "Grondsoort > 50% Veen",
    "3": "Grondsoort > 50% Zand",
    "4": "Grondsoort > 50% Löss",
    "5": "Grondsoort > 50% Zand of Löss",
    "6": "Grondsoort > 50% Klei of Veen",
  },
  /** Ground Types */
  TypeGrond: {
    "1": "Natuurgrond",
    "2": "Primaire Waterkering",
    "3": "Beide",
  },
  /** Sampling Protocol */
  BemonsteringProtocol: {
    "1": "Ja, laten bemonsteren volgens het Bemonsteringsprotocol",
    "2": "Nee, niet laten bemonsteren volgens het Bemonsteringsprotocol",
  },
  /** Catch Crop (Nateelt) Manure Indicator */
  IndNateeltMest: {
    "1": "Ik teel een nateelt",
    "2": "Mijn hoofdteelt is een winterteelt",
    "3": "Ik zet mijn perceel onder water tegen onkruid en ziektes (inundatie)",
  },
  /** Sowing Date (Inzaaidatum) codes for Catch Crops */
  InzaaidatumCode: {
    "1": "Uiterlijk 1 oktober",
    "2": "Vanaf 2 oktober, maar uiterlijk 15 oktober",
    "3": "Vanaf 16 oktober, maar uiterlijk 31 oktober",
    "4": "Vanaf 1 november",
    "5": "Na 1 oktober",
  },
  /** Severity Codes (CL415) */
  SeverityCode: {
    FATAAL: "Fataal",
    FOUT: "Fout",
    WAARSCHUWING: "Waarschuwing",
    INFO: "Informatie",
  },
  /** Quality Indicator Codes (CL413) */
  IndicatorCode: {
    KI001: "De gebruikstitel is gedurende (een deel van) de looptijd van dit perceel ongeldig.",
    KI002: "De gewascode is gedurende (een deel van) de looptijd van dit perceel ongeldig.",
    KI003:
      "Dit perceel valt gedurende (een deel van) de looptijd geheel of gedeeltelijk buiten de topografische perceelsgrenzen.",
    KI004:
      "Dit perceel heeft gedurende (een deel van) de looptijd geheel of gedeeltelijk overlap met een perceel van een andere gebruiker.",
    KI005:
      "Dit perceel heeft gedurende (een deel van) de looptijd geheel of gedeeltelijk overlap met een van uw andere percelen.",
    KI2210: "Validatie op bedrijfsperceel voor Regelingspercelen.",
    KI12030: "Valideer gewascodes op bedrijfspercelen die buiten RRP moeten liggen",
    KI12051: "Overlap/overschrijding BPL met RRP fysiek voorkomen",
    KI21020: "Ongeldige grondsoort ingevuld",
    KI111001: "Validatie op grondsoort",
  },
  /** Change Type Codes */
  ChangeTypeCode: {
    "10": "Ongewijzigd",
    "20": "Gewijzigd",
    "30": "Nieuw",
    "60": "Geannuleerd",
  },
  /** Mutation Causes */
  Cause: {
    A: "Actief (Nieuw)",
    D: "Verwijderd",
    AR: "Andere reden",
  },
  /** BRP Crop Types (extracted from fdm-data) */
  CropTypeCode: {
    "172": "tuinbouwzaden",
    "174": "bloemzaden open grond",
    "175": "bloemkwekerijgewassen (inclusief bloemzaden)",
    "176": "bloembollen en - knollen",
    "212": "fruit",
    "229": "boomkwekerij en vaste planten",
    "233": "tarwe, winter-",
    "234": "tarwe, zomer-",
    "235": "gerst, winter-",
    "236": "gerst, zomer-",
    "237": "rogge (geen snijrogge)",
    "238": "haver",
    "239": "erwten, groene, droog te oogsten (geen conserven)",
    "240": "schokkers",
    "241": "kapucijners (en grauwe erwten)",
    "242": "bonen, bruine-",
    "243": "bonen, veld-(oa duive-, paarde-, wierbonen)(droog te oogsten",
    "244": "erwten, groene/gele (groen te oogsten)",
    "246": "karwijzaad",
    "247": "blauwmaanzaad",
    "249": "vlas, vezel- (niet voor zaaizaad)",
    "256": "bieten, suiker-",
    "257": "bieten, voeder-",
    "258": "luzerne",
    "259": "mais, snij-",
    "262": "uien, zaai-",
    "263": "uien, zilver-",
    "265": "grasland, blijvend",
    "266": "grasland, tijdelijk",
    "294": "boomkwekerijgewassen en vaste planten, pot- en containerveld",
    "308": "erwten (droog te oogsten)",
    "311": "bonen, veld- (onder andere duiven-, paarden-, wierbonen)",
    "314": "triticale",
    "316": "mais, korrel-",
    "317": "mais, corncob mix",
    "331": "grasland, natuurlijk. met landbouwactiviteiten.",
    "332": "grasland, natuurlijk. hoofdfunctie natuur.",
    "333":
      "rand, grenzend aan blijvend grasland of een blijvende teelt, hoofdzakelijk bestaand uit blijvend gras",
    "334": "rand, grenzend aan bouwland, hoofdzakelijk bestaand uit blijvend gras",
    "335": "natuurterreinen (incl. heide)",
    "336":
      "grasland, natuurlijk. areaal met een natuurbeheertype dat overwegend voor landbouwactiviteiten-glb wordt gebruikt",
    "337": "bufferstrook, rand (inclusief eventuele oevervegetatie)",
    "338": "rand, liggend op bouwland en direct grenzend aan bos. geen landbouwproductie.",
    "343": "sloot",
    "344":
      "rand, grenzend aan blijvend grasland of een blijvende teelt, hoofdzakelijk bestaand uit een ander gewas dan gras",
    "345": "rand, grenzend aan bouwland, hoofdzakelijk bestaand uit een ander gewas dan gras",
    "346": "tagetes erecta (afrikaantje)",
    "347": "tagetes patula (afrikaantje)",
    "370":
      "rand, grenzend aan blijvend grasland of een blijvende teelt, hoofdzakelijk bestaand uit tijdelijk gras",
    "372": "rand, grenzend aan bouwland, hoofdzakelijk bestaand uit tijdelijk gras",
    "375": "hop",
    "381": "teff",
    "382": "spelt",
    "383": "graszaad",
    "426": "overige groenbemesters, vlinderbloemige-",
    "427": "overige groenbemesters, niet-vlinderbloemige-",
    "428": "gele mosterd",
    "511": "cichorei",
    "513": "kanariezaad",
    "515": "zonnebloemen",
    "516": "miscanthus (olifantsgras)",
    "636": "saffloer",
    "637": "vrouwenmantel",
    "652": "meekrap",
    "653": "teunisbloem",
    "654": "brandnetel",
    "655": "zwarte mosterd",
    "656": "zonnekroon",
    "657": "drachtplanten",
    "658": "graansorgho",
    "659": "boekweit",
    "660": "gierst",
    "661": "overige granen",
    "662": "bos (sbl-regeling)",
    "663": "lupinen, niet bittere",
    "664": "raapzaad",
    "665": "sojabonen",
    "666": "vlas, olie-. lijnzaad niet van vezelvlas",
    "669": "zwaardherik (aaltjesvanggewas)",
    "670": "japanse haver",
    "671": "raketblad (aaltjesvanggewas)",
    "672": "groenten open grond (inclusief groentezaden)",
    "794": "woudbomen met korte omlooptijd (excl. wilgenhakhout)",
    "795": "wilgenhakhout",
    "796": "kerstbomen",
    "799": "klaver, rode",
    "800": "rolklaver",
    "801": "esparcette",
    "802": "wikke, bonte",
    "803": "wikke, voeder-",
    "804": "klaverzaad",
    "814": "mais, suiker-",
    "853": "bonen, tuin- (droog te oogsten) (geen consumptie)",
    "854": "bonen, tuin- (groen te oogsten)",
    "859": "aardappelen, zetmeel geleverd aan buitenland",
    "863": "bos zonder herplantplicht",
    "864": "bos (set aside regeling)",
    "944": "hennep, vezel-",
    "964": "dahlia, overige bloemkwekerijgewassen",
    "965": "dahlia, droogbloemen",
    "967": "gladiool, overige bloemkwekerijgewassen",
    "968": "gladiool, droogbloemen",
    "970": "hyacint, overige bloemkwekerijgewassen",
    "971": "hyacint, droogbloemen",
    "973": "iris, overige bloemkwekerijgewassen",
    "974": "iris, droogbloemen",
    "976": "krokus, overige bloemkwekerijgewassen",
    "977": "krokus, droogbloemen",
    "979": "lelie, overige bloemkwekerijgewassen",
    "980": "lelie, droogbloemen",
    "982": "narcis, overige bloemkwekerijgewassen",
    "983": "narcis, droogbloemen",
    "985": "tulp, overige bloemkwekerijgewassen",
    "986": "tulp, droogbloemen",
    "988": "zantedeschia, overige bloemkwekerijgewassen",
    "989": "zantedeschia, droogbloemen",
    "991": "overige bloemen, overige bloemkwekerijgewassen",
    "992": "overige bloemen, droogbloemen",
    "994": "amaryllis, overige bloemkwekerijgewassen",
    "995": "amaryllis, droogbloemen",
    "997": "dahlia, bloembollen en - knollen",
    "998": "gladiool, bloembollen en - knollen",
    "999": "hyacint, bloembollen en - knollen",
    "1000": "iris, bloembollen en -knollen",
    "1001": "krokus, bloembollen en - knollen",
    "1002": "lelie, bloembollen en -knollen",
    "1003": "narcis, bloembollen en -knollen",
    "1004": "tulp, bloembollen en -knollen",
    "1005": "zantedeschia, bloembollen en -knollen",
    "1006": "overige bloemen, bloembollen en -knollen",
    "1007": "amaryllis, bloembollen en -knollen",
    "1010": "sierui, overige bloemkwekerijgewassen",
    "1011": "sierui, droogbloemen",
    "1012": "sierui, bloembollen en -knollen",
    "1013": "blauw druifje, overige bloemkwekerijgewassen",
    "1014": "blauw druifje, droogbloemen",
    "1015": "blauw druifje, bloembollen en -knollen",
    "1016": "kuifhyacint, overige bloemkwekerijgewassen",
    "1017": "kuifhyacint, droogbloemen",
    "1018": "kuifhyacint, bloembollen en -knollen",
    "1019": "valeriaan, productie",
    "1020": "valeriaan, zaden en opkweekmateriaal",
    "1021": "knoflook",
    "1022": "quinoa",
    "1023": "pastinaak, productie",
    "1024": "pastinaak, zaden en opkweekmateriaal",
    "1025": "pioenroos, overige bloemkwekerijgewassen",
    "1026": "pioenroos, droogbloemen",
    "1027": "pioenroos, bloembollen en -knollen",
    "1028": "lavas (maggiplant), productie",
    "1029": "lavas (maggiplant), zaden en opkweekmateriaal",
    "1030": "wilde marjolein (oregano), productie",
    "1031": "wilde marjolein (oregano), zaden en opkweekmateriaal",
    "1032": "goudsbloem",
    "1033": "igniscum candy",
    "1034": "kanariezaad",
    "1035": "naaldaar (setaria)",
    "1036": "wortelpeterselie",
    "1037": "peterselie, productie",
    "1038": "peterselie, zaden en opkweekmateriaal",
    "1039": "chrysant, overige bloemkwekerijgewassen",
    "1040": "chrysant, droogbloemen",
    "1042": "angelica, productie",
    "1043": "angelica, zaden en opkweekmateriaal",
    "1044": "papaver (klaproos)",
    "1045": "adonis",
    "1046": "vergeet mij nietje",
    "1047": "cranberry",
    "1048": "echinacea (zonnehoed), productie",
    "1049": "echinacea (zonnehoed), zaden en opkweekmateriaal",
    "1050": "leeuwenbekjes",
    "1051": "iris, bolvormend",
    "1052": "iris, rhizoomvormend",
    "1053": "palmen, pot- en containervelden",
    "1054": "pioenroos, vermeerdering",
    "1055": "chrysant, vermeerdering",
    "1067": "bos- en haagplanten, open grond",
    "1068": "buxus, open grond",
    "1069": "ericaceae (zoals erica, calluna, rododendron, azalea), open grond",
    "1070": "laanbomen/parkbomen, onderstammen, open grond",
    "1071": "laanbomen/parkbomen, opzetters, open grond",
    "1072": "laanbomen/parkbomen, spillen, open grond",
    "1073": "rozenstruiken (incl, zaailingen en onderstammen), open grond",
    "1074": "sierconiferen, open grond",
    "1075": "sierheesters en klimplanten, open grond",
    "1076": "trek- en besheesters, open grond",
    "1077": "vruchtbomen, moerbomen, open grond",
    "1078": "vruchtbomen, onderstammen, open grond",
    "1079": "vruchtbomen, overig, open grond",
    "1080": "vaste planten, open grond",
    "1081": "bos- en haagplanten, pot- en containerveld",
    "1082": "buxus, pot- en containerveld",
    "1083": "ericaceae (zoals erica, calluna, rododendron, azalea), pot- en containerveld",
    "1084": "laanbomen/parkbomen, onderstammen, pot- en containerveld",
    "1085": "laanbomen/parkbomen, opzetters, pot- en containerveld",
    "1086": "laanbomen/parkbomen, spillen, pot- en containerveld",
    "1087": "rozenstruiken (incl, zaailingen en onderstammen), pot- en containerveld",
    "1088": "sierconiferen, pot- en containerveld",
    "1089": "sierheesters en klimplanten, pot- en containerveld",
    "1090": "trek- en besheesters, pot- en containerveld",
    "1091": "vruchtbomen, moerbomen, pot- en containerveld",
    "1092": "vruchtbomen, onderstammen, pot- en containerveld",
    "1093": "vruchtbomen, overig, pot- en containerveld",
    "1094": "vaste planten, pot- en containerteelt",
    "1095": "appels. aangeplant lopende seizoen.",
    "1096": "appels. aangeplant voorafgaande aan lopende seizoen.",
    "1097": "peren. aangeplant lopende seizoen.",
    "1098": "peren. aangeplant voorafgaande aan lopende seizoen.",
    "1099": "wijndruiven",
    "1100": "overige pit- en steenvruchten (zoals perziken, tafeldruiven)",
    "1570": "klaverzaad",
    "1574": "definitief aan de landbouw onttrokken cultuurgrond",
    "1575": "faunaranden",
    "1697": "hazelnoten",
    "1698": "walnoten",
    "1869": "bessen, blauwe",
    "1870": "pruimen",
    "1872": "kersen, zuur (opbrengst bestemd voor verwerkende industrie)",
    "1873": "bessen, zwarte (opbrengst verwerkt voor verwerkende industrie)",
    "1874": "overig kleinfruit (zoals kruisbessen, kiwi's)",
    "1876": "snijgroen",
    "1909": "aardappelen, consumptie- op kleigrond",
    "1910": "aardappelen, consumptie- op zand-/veengrond",
    "1911": "aardappelen, cons. op kleigrond (vroeg, loofver voor 15-07)",
    "1912": "aardappelen, cons. op zand/veen (vroeg, loofver voor 15-07)",
    "1914": "graszaad, overig",
    "1915": "graszaad, rietzwenkgras",
    "1916": "graszaad, veldbeemd",
    "1917": "graszaad, roodzwenkgras, 1e jaar",
    "1918": "graszaad, roodzwenkgras, overjarig",
    "1919": "graszaad, westerwolds",
    "1920": "graszaad, italiaans",
    "1921": "graszoden",
    "1922": "koolzaad, winter (incl. boterzaad)",
    "1923": "koolzaad, zomer (incl. boterzaad)",
    "1925": "overige akkerbouwgewassen",
    "1926": "agrarisch natuurmengsel",
    "1927": "overige akkerbouwgewassen",
    "1928": "aardappelrassen, poot- op kleigrond",
    "1929": "aardappelrassen, poot- op zand-/veengrond",
    "1930": "tagetes (zand, loss) (geen groene braak)",
    "1931": "uien, poot- en plant- (incl. sjalotten)",
    "1932": "uien, poot en plant, 1e jaars",
    "1933": "uien, poot en plant, 2e jaars",
    "1934": "sjalotten",
    "1935": "maiskolvensilage",
    "1936": "bos, blijvend, met herplantplicht",
    "1940": "voedselbos",
    "1949": "aardperen",
    "1950": "onbekend/gewas niet opgegeven",
    "1959": "dummycode voor dummypercelen",
    "2014": "aardappelen, consumptie",
    "2015": "aardappelen, poot nak",
    "2016": "aardappelen, poot tbm",
    "2017": "aardappelen, zetmeel",
    "2025": "aardappelen, bestrijdingsmaatregel am",
    "2026": "braak met bos (sbl-regeling na 28 juni 1995)",
    "2027": "bos (sbl-regeling)",
    "2029": "braak, natuur-",
    "2030": "graszaad, engels raai 1e jaar",
    "2031": "graszaad, engels raai overjarig",
    "2032": "mais, energie-",
    "2033": "onbeteelde grond, tijdelijk",
    "2297": "woudbomen met korte omlooptijd",
    "2298": "groenbemesters, vlinderbloemige",
    "2299": "groenbemesters, niet-vlinderbloemige",
    "2300": "onbeteelde grond vanwege een teeltverbod/ontheffing",
    "2301": "natuurlijk grasland with hoofdfunctie landbouw",
    "2302": "natuurlijk grasland (begraasd) met beperkte landbouwact.",
    "2303": "overige natuurterreinen",
    "2304": "heide, begraasd",
    "2325": "bessen, rode",
    "2326": "frambozen",
    "2327": "bramen",
    "2328": "kersen, zoet",
    "2617": "boomgroep",
    "2618": "windhaag, in een perceel fruitteelt",
    "2619": "bossingel",
    "2620": "poel en klein historisch water",
    "2621": "houtwal en houtsingel",
    "2622": "elzensingel",
    "2624": "knip- of scheerheg",
    "2625": "struweelhaag",
    "2626": "laan",
    "2628": "hoogstamboomgaard",
    "2629": "struweelrand",
    "2630": "hakhoutbosje",
    "2631": "griendje",
    "2633": "rietzoom en klein rietperceel",
    "2634": "natuurvriendelijke oever",
    "2635": "wandelpad over boerenland",
    "2636": "leibomen",
    "2637": "schurvelingen en zandwallen",
    "2638": "landschapselement, overig",
    "2639": "water, overig",
    "2640": "geisoleerde boom (anders dan knotboom)",
    "2641": "bomenrij (anders dan knotboom)",
    "2642": "bosje",
    "2643": "knotboom, bomen in rij",
    "2644": "knotboom, geisloleerde boom",
    "2645": "notenbomen",
    "2650": "erwten inclusief schokkers (droog te oogsten)",
    "2651": "bieten, voeder- (inclusief aardperen)",
    "2652": "granen, overig",
    "2653": "graszaad (inclusief klaverzaad)",
    "2700": "aardbeien open grond, vermeerdering",
    "2701": "aardbeien open grond, wachtbed",
    "2702": "aardbeien open grond, productie",
    "2703": "aardbeien open grond, zaden en opkweekmateriaal",
    "2704": "aardbeien op stellingen, vermeerdering",
    "2705": "aardbeien op stellingen, wachtbed",
    "2706": "aardbeien op stellingen, productie",
    "2707": "aardbeien op stellingen, zaden en opkweekmateriaal",
    "2708": "andijvie, productie",
    "2709": "andijvie, zaden en opkweekmateriaal",
    "2710": "asperges, oppervlakte die productie oplevert",
    "2711": "asperges, oppervlakte die nog geen productie oplevert",
    "2712": "asperges, zaden en opkweekmateriaal",
    "2713": "bloemkool, productie",
    "2714": "bloemkool, zaden en opkweekmateriaal",
    "2715": "boerenkool, productie",
    "2716": "boerenkool, zaden en opkweekmateriaal",
    "2717": "bospeen, productie",
    "2718": "bospeen, zaden en opkweekmateriaal",
    "2719": "broccoli, productie",
    "2720": "broccoli, zaden en opkweekmateriaal",
    "2721": "chinese kool, productie",
    "2722": "chinese kool, zaden en opkweekmateriaal",
    "2723": "courgette, productie",
    "2724": "courgette, zaden en opkweekmateriaal",
    "2725": "knolselderij, productie",
    "2726": "knolselderij, zaden en opkweekmateriaal",
    "2727": "knolvenkel/venkel, productie",
    "2728": "knolvenkel/venkel, zaden en opkweekmateriaal",
    "2729": "komkommer, productie",
    "2730": "komkommer, zaden en opkweekmateriaal",
    "2731": "augurk, productie",
    "2732": "augurk, zaden en opkweekmateriaal",
    "2733": "meloen, productie",
    "2734": "meloen, zaden en opkweekmateriaal",
    "2735": "pompoen, productie",
    "2736": "pompoen, zaden en opkweekmateriaal",
    "2737": "koolraap, productie",
    "2738": "koolraap, zaden en opkweekmateriaal",
    "2739": "koolrabi, productie",
    "2740": "koolrabi, zaden en opkweekmateriaal",
    "2741": "kroten/rode bieten, productie",
    "2742": "kroten/rode bieten, zaden en opkweekmateriaal",
    "2743": "kruiden, productie",
    "2744": "kruiden, zaden en opkweekmateriaal",
    "2745": "paksoi, productie",
    "2746": "paksoi, zaden en opkweekmateriaal",
    "2747": "peulen, productie",
    "2748": "peulen, zaden en opkweekmateriaal",
    "2749": "prei, productie",
    "2750": "prei, zaden en opkweekmateriaal",
    "2751": "pronkbonen, productie",
    "2752": "pronkbonen, zaden en opkweekmateriaal",
    "2753": "raapstelen, productie",
    "2754": "raapstelen, zaden en opkweekmateriaal",
    "2755": "rabarber, productie",
    "2756": "rabarber, zaden en opkweekmateriaal",
    "2757": "radijs, productie",
    "2758": "radijs, zaden en opkweekmateriaal",
    "2759": "rodekool, productie",
    "2760": "rodekool, zaden en opkweekmateriaal",
    "2761": "savooiekool, productie",
    "2762": "savooiekool, zaden en opkweekmateriaal",
    "2763": "schorseneren, productie",
    "2764": "schorseneren, zaden en opkweekmateriaal",
    "2765": "selderij, bleek- en groen-, productie",
    "2766": "selderij, bleek- en groen-, zaden en opkweekmateriaal",
    "2767": "sla, ijsberg-, productie",
    "2768": "sla, ijsberg-, zaden en opkweekmateriaal",
    "2769": "sla, radicchio rosso, productie",
    "2770": "sla; radicchio rosso, zaden en opkweekmateriaal",
    "2771": "sla, overig, productie",
    "2772": "sla, overig, zaden en opkweekmateriaal",
    "2773": "spinazie, productie",
    "2774": "spinazie, zaden en opkweekmateriaal",
    "2775": "spitskool, productie",
    "2776": "spitskool, zaden en opkweekmateriaal",
    "2777": "spruitkool/spruitjes, productie",
    "2778": "spruitkool/spruitjes, zaden en opkweekmateriaal",
    "2779": "stamsperziebonen (=stamslabonen), productie",
    "2780": "stamsperziebonen (=stamslabonen), zaden en opkweekmateriaal",
    "2781": "stoksnijbonen en stokslabonen, productie",
    "2782": "stoksnijbonen en stokslabonen, zaden en opkweekmateriaal",
    "2783": "waspeen, productie",
    "2784": "waspeen, zaden en opkweekmateriaal",
    "2785": "winterpeen, productie",
    "2786": "winterpeen, zaden en opkweekmateriaal",
    "2787": "witlofwortel, productie",
    "2788": "witlofwortel, zaden en opkweekmateriaal",
    "2789": "witte kool, productie",
    "2790": "witte kool, zaden en opkweekmateriaal",
    "2791": "overige niet genoemde bladgewassen, productie",
    "2792": "overige niet genoemde bladgewassen, zaden en opkweekmateriaal",
    "2793": "overige niet genoemde groenten, productie",
    "2794": "overige niet genoemde groenten, zaden en opkweekmateriaal",
    "2795": "bloemkool, winter, productie",
    "2796": "bloemkool, winter, zaden en opkweekmateriaal",
    "2797": "bloemkool, zomer, productie",
    "2798": "bloemkool, zomer, zaden en opkweekmateriaal",
    "2799": "prei, winter, productie",
    "2800": "prei, winter, zaden en opkweekmateriaal",
    "2801": "prei, zomer, productie",
    "2802": "prei, zomer, zaden en opkweekmateriaal",
    "2951": "aardappelen, consumptie op klei/loessgrond",
    "3055": "lisdodde",
    "3500": "klaver, alexandrijnse",
    "3501": "beemdlangbloem",
    "3502": "bladkool",
    "3503": "bladraap",
    "3504": "bladrammenas",
    "3505": "deder",
    "3506": "engels raaigras",
    "3507": "ethiopische mosterd",
    "3508": "facelia",
    "3509": "festulolium",
    "3510": "boekweit",
    "3511": "klaver, incarnaat",
    "3512": "italiaans raaigras",
    "3513": "westerwolds raaigras",
    "3514": "niger",
    "3515": "klaver, perzische",
    "3516": "rietzwenkgras",
    "3517": "sarepta mosterd/caliente",
    "3518": "seradelle",
    "3519": "soedangras/sorghum",
    "3520": "spurrie",
    "3521": "stoppelknollen",
    "3522": "timothee",
    "3523": "veldbeemdgras",
    "3524": "klaver, witte",
    "3718": "grasland, natuurlijk",
    "3719": "heide",
    "3720": "faunaranden, grasland",
    "3721": "faunaranden, bouwland",
    "3722": "overige natuurterreinen",
    "3730": "aardappelen, poot op klei/loessgrond (nak)",
    "3731": "aardappelen, poot op zand/veengrond (nak)",
    "3732": "aardappelen, zetmeel (incl. tbm-pootgoed)",
    "3736": "vlas, vezel-",
    "3792": "aardappelen, consumptie op zand/veengrond",
    "3801": "tijdelijk onbeteelde grond, i.v.m. publieke werken",
    "3802": "tijdelijk onbeteelde grond, anders dan voor publieke werken",
    "3803":
      "rand, grenzend aan bouwland, hoofdzakelijk bestaand uit een ander gewas dan gras. (ea: beheer)",
    "3804":
      "rand, grenzend aan bouwland, hoofdzakelijk bestaand uit een ander gewas dan gras. (ea: onbeheerd)",
    "3805": "rietzwenkgras, industriegras",
    "3806": "boomkwekerijgewassen en vaste planten, open grond",
    "3807": "rietzwenkgras, anders dan voor industriegras",
    "3808": "roodzwenkgras",
    "6520": "azolla",
    "6521": "wilde rijst",
    "6522": "riet",
    "6632": "zoete aardappelen",
    "6636": "naakte haver",
    "6660": "uien, gele zaai-",
    "6664": "uien, rode zaai-",
    "6746": "beemdlangbloem, graszaad",
    "6748": "beemdlangbloem, groenbemesting, vanggewas",
    "6749": "bieslook",
    "6750": "engels raaigras, graszaad",
    "6751": "engels raaigras, groenbemesting, vanggewas",
    "6752": "festulolium, graszaad",
    "6753": "festulolium, groenbemesting, vanggewas",
    "6754": "italiaans raaigras, graszaad",
    "6755": "italiaans raaigras, groenbemesting, vanggewas",
    "6756": "klaver, alexandrijnse, groenbemesting, vanggewas",
    "6757": "klaver, alexandrijnse, klaverzaad",
    "6758": "klaver, incarnaat, groenbemesting, vanggewas",
    "6759": "klaver, incarnaat, klaverzaad",
    "6760": "klaver, perzische, groenbemesting, vanggewas",
    "6761": "klaver, perzische, klaverzaad",
    "6762": "klaver, rode, groenbemesting, vanggewas",
    "6763": "klaver, rode, klaverzaad",
    "6764": "klaver, witte, groenbemesting, vanggewas",
    "6765": "klaver, witte, klaverzaad",
    "6766": "lamsoor",
    "6767": "linzen",
    "6768": "overig graszaad",
    "6769": "overig klaverzaad",
    "6782": "rietzwenkgras, graszaad",
    "6783": "rietzwenkgras, groenbemesting, vanggewas",
    "6784": "roodzwenkgras, graszaad",
    "6785": "roodzwenkgras, groenbemesting, vanggewas",
    "6786": "timothee, graszaad",
    "6787": "timothee, groenbemesting, vanggewas",
    "6788": "veldbeemdgras, graszaad",
    "6789": "veldbeemdgras, groenbemesting, vanggewas",
    "6790": "westerwolds raaigras, graszaad",
    "6791": "westerwolds raaigras, groenbemesting, vanggewas",
    "6792": "zeekraal",
    "6793": "graften",
    "6794": "groene braak, spontane opkomst",
    "6795": "liatris, bloembollen en -knollen",
    "6796": "liatris, droogbloemen",
    "6797": "liatris, overige bloemkwekerijgewassen",
    "6798": "perceel bedekt met gewasresten (mulching)",
    "6799": "rijst",
    "6800": "ruigtes op landbouwpercelen",
    "6801": "schouwpad",
    "6802": "sedum",
    "6803": "sneeuwklokje, bloembollen en -knollen",
    "6804": "sneeuwklokje, droogbloemen",
    "6805": "sneeuwklokje, overige bloemkwekerijgewassen",
    "6806": "snijrogge",
    "6807": "stroken wild gras",
    "6808": "tuunwallen",
    "6809": "voederhaag",
    "7121": "bonen, witte-",
    "7122": "yacon",
    "7124": "raapzaad, winter",
    "7125": "overige groenbemesters, niet-vlinderbloemige-, niet zijnde gras",
    "7126": "overige gras, groenbemesting, vanggewas",
    "7127": "rietland",
    "7128": "rietkraag/rietzoom",
    "7129": "rogge, groenvoedergewas",
    "7130": "rogge, korrelgewas",
    "7131": "rogge, groenbemesting, vanggewas",
    "7134": "riet in water, anders dan een subsidiabele sloot",
    "7135": "riet in een subsidiabele sloot",
    "7137": "bonen, overig",
    "7138": "palmkool",
  },
}

/**
 * Gets a descriptive label for a code from a specific list.
 *
 * @param listName The name of the codelist.
 * @param code The code to look up.
 * @param fallback Optional fallback value if code is not found.
 */
export function getLabel(
  listName: string,
  code: string | number,
  fallback?: string,
): string | undefined {
  const list = CODELISTS[listName]
  if (!list) return fallback
  const label = list[String(code)]
  return label || fallback
}

/**
 * Maps a "J" / "N" (Ja/Nee) string to a boolean.
 */
export function mapIndicator(value: any): boolean | null {
  if (value === "J") return true
  if (value === "N") return false
  return null
}
