import xml2js from 'xml2js';
import type { RvoClientConfig, BedrijfspercelenOptions, BedrijfspercelenResponse, RvoAuthTvsConfig, RvoTokenResponse } from './types';
import { TvsAuth } from './auth/tvs';
import { buildBedrijfspercelenRequest } from './soap/builder';
import { transformBedrijfspercelenToGeoJSON } from './transformers/bedrijfspercelen';

// Default Endpoints for different environments
const ENDPOINTS = {
  acceptance: {
    tvsAuthorize: 'https://pp2.toegang.overheid.nl/kvo/authorize',
    tvsToken: 'https://pp2.toegang.overheid.nl/kvo/token',
    ediCropTvs: 'https://edicrop-acc.agro.nl/edicrop/EdiCrop-WebService/v2',
    ediCropAba: 'https://edicrop-acc.agro.nl/edicrop/EdiCropService',
  },
  production: {
    tvsAuthorize: 'https://toegang.overheid.nl/kvo/authorize',
    tvsToken: 'https://toegang.overheid.nl/kvo/token',
    ediCropTvs: 'https://edicrop.agro.nl/edicrop/EdiCrop-WebService/v2',
    ediCropAba: 'https://edicrop.agro.nl/edicrop/EdiCropService',
  },
};

// Scopes for eHerkenning (URNs) based on environment
const EHERKENNING_SCOPES = {
  acceptance: 'urn:nl-eid-gdi:1.0:ServiceUUID:44345953-4138-4f53-3454-593459414d45',
  production: 'urn:nl-eid-gdi:1.0:ServiceUUID:37534755-4536-4152-5747-595850325434',
};

/**
 * RVO Service types supported by the client.
 * - `'opvragenBedrijfspercelen'`: Retrieve crop fields (EDI-Crop).
 * - `'muterenBedrijfspercelen'`: Mutate/Update crop fields.
 */
export type RvoService = 'opvragenBedrijfspercelen' | 'muterenBedrijfspercelen';

const SERVICE_SCOPES: Record<RvoService, string> = {
  opvragenBedrijfspercelen: 'RVO-WS.GEO.bp.lezen',
  muterenBedrijfspercelen: 'RVO-WS.GEO.bp.muteren',
};

/**
 * Options for generating the Authorization URL.
 */
export interface AuthUrlOptions {
  /**
   * The service you want to access.
   * This determines the scope requested from eHerkenning.
   * @default 'opvragenBedrijfspercelen'
   */
  service?: RvoService;
  /**
   * A unique string value used to prevent CSRF attacks.
   * If not provided, a random UUID will be generated by the `TvsAuth` class (though passing it explicitly is recommended so you can verify it).
   */
  state?: string;
}

/**
 * The main client for interacting with RVO webservices.
 * Handles authentication (ABA or TVS/eHerkenning) and SOAP request execution.
 */
export class RvoClient {
  private config: RvoClientConfig;
  private tvsAuth?: TvsAuth;
  private accessToken?: string;

  /**
   * Creates a new instance of the RvoClient.
   * @param config Configuration options for the client.
   */
  constructor(config: RvoClientConfig) {
    this.config = {
      authMode: 'TVS', // Default authentication mode
      environment: 'acceptance', // Default environment
      ...config
    };

    const env = this.config.environment!;
    const envEndpoints = ENDPOINTS[env];

    // Override with explicit endpoints if provided in config
    const ediCropTvsUrl = this.config.ediCropUrl || envEndpoints.ediCropTvs;
    const ediCropAbaUrl = this.config.ediCropAbaUrl || envEndpoints.ediCropAba;

    // Configure TVS Auth
    if (this.config.authMode === 'TVS') {
      if (!this.config.tvs) {
        throw new Error('TVS authentication mode selected but TVS configuration is missing.');
      }
      const tvsAuthConf: RvoAuthTvsConfig = {
        authorizeEndpoint: this.config.tvs.authorizeEndpoint || envEndpoints.tvsAuthorize,
        tokenEndpoint: this.config.tvs.tokenEndpoint || envEndpoints.tvsToken,
        ...this.config.tvs, // Spread existing TVS config to allow overrides
      };
      this.tvsAuth = new TvsAuth(tvsAuthConf);
    }

    // Update config with resolved URLs for internal use
    this.config.ediCropUrl = ediCropTvsUrl;
    this.config.ediCropAbaUrl = ediCropAbaUrl;
  }

  // --- Auth Methods (TVS) ---

  /**
   * Generates the authorization URL for the specified RVO service (TVS/eHerkenning only).
   * Redirect the user to this URL to start the login process.
   *
   * @param options Options for generating the URL, including the target service and state.
   * @returns The fully constructed authorization URL.
   * @throws Error if authentication mode is not 'TVS'.
   */
  public getAuthorizationUrl(options: AuthUrlOptions = {}): string {
    if (this.config.authMode !== 'TVS' || !this.tvsAuth) {
      throw new Error('Authentication mode is not TVS or TVS configuration is missing.');
    }

    const service = options.service || 'opvragenBedrijfspercelen';
    const env = this.config.environment || 'acceptance';
    const eherkenningScope = EHERKENNING_SCOPES[env];
    const serviceScope = SERVICE_SCOPES[service];

    // Combine scopes separated by space
    const fullScope = `${serviceScope} ${eherkenningScope}`;

    return this.tvsAuth.getAuthorizationUrl(fullScope, options.state);
  }

  /**
   * Exchanges the authorization code received from the RVO redirect for an access token.
   * (TVS/eHerkenning only).
   *
   * @param code The authorization code from the query parameters of the redirect URI.
   * @returns A promise resolving to the token response (containing `access_token`, `expires_in`, etc.).
   * @throws Error if authentication mode is not 'TVS' or if the token exchange fails.
   */
  public async exchangeAuthCode(code: string): Promise<RvoTokenResponse> {
    if (this.config.authMode !== 'TVS' || !this.tvsAuth) {
      throw new Error('Authentication mode is not TVS or TVS configuration is missing.');
    }
    const tokenData = await this.tvsAuth.getAccessToken(code);
    this.accessToken = tokenData.access_token;
    return tokenData;
  }

  /**
   * Manually sets the OAuth 2.0 access token.
   * Useful if you handle token storage/refreshing external to this class instance.
   *
   * @param token The access token string.
   */
  public setAccessToken(token: string) {
    this.accessToken = token
  }

  // --- Service Methods ---

  /**
   * Calls the `OpvragenBedrijfspercelen` (GetCropFields) SOAP service.
   * Retrieves registered crop fields for a farm.
   *
   * @param options Optional parameters for the request (farm ID, date range).
   * @returns A promise resolving to the parsed XML response from RVO.
   * @throws Error if authentication fails or the SOAP request returns an error.
   */
  public async opvragenBedrijfspercelen(
    options: BedrijfspercelenOptions = {},
  ): Promise<BedrijfspercelenResponse> {
    const isTvs = this.config.authMode === "TVS"

    if (isTvs && !this.accessToken) {
      throw new Error(
        "Access token is missing. Authenticate via TVS first or set the access token.",
      )
    }
    if (!isTvs && (!this.config.aba || !this.config.aba.username)) {
      throw new Error(
        "ABA authentication mode selected but ABA username is missing.",
      )
    }

    const soapXml = buildBedrijfspercelenRequest({
      farmId: options.farmId,
      periodBeginDate: options.periodBeginDate,
      periodEndDate: options.periodEndDate,
      abaCredentials: isTvs ? undefined : this.config.aba,
      issuerId: this.config.clientName,
      senderId: this.config.clientName,
    })

    const url = isTvs ? this.config.ediCropUrl! : this.config.ediCropAbaUrl!

    const headers: Record<string, string> = {
      "Content-Type": "text/xml; charset=utf-8",
    }

    if (isTvs && this.accessToken) {
      headers["Authorization"] = `Bearer ${this.accessToken}`
    }

    try {
      const response = await fetch(url, {
        method: "POST",
        headers,
        body: soapXml,
      })

      const responseText = await response.text()

      if (!response.ok) {
        throw new Error(`Request failed: ${response.status} - ${responseText}`)
      }

      const parser = new xml2js.Parser({
        explicitArray: false,
        tagNameProcessors: [xml2js.processors.stripPrefix],
      })
      const result = await parser.parseStringPromise(responseText)

      if (options.outputFormat === "geojson") {
        return transformBedrijfspercelenToGeoJSON(result)
      }

      return result
    } catch (error: any) {
      throw error
    }
  }
}
