import xml2js from "xml2js"
import type {
  RvoClientConfig,
  BedrijfspercelenOptions,
  BedrijfspercelenResponse,
  RvoAuthTvsConfig,
  RvoTokenResponse,
  MuterenRequestOptions,
  MuterenResponse,
  ProcesVoortgangResponse,
  ValidatieResultaatResponse,
  TanResponse,
  TransactionResponse,
} from "./types"
import { TvsAuth } from "./auth/tvs"
import {
  buildBedrijfspercelenRequest,
  buildMuterenRequest,
  buildProcesVoortgangRequest,
  buildValidatieResultaatRequest,
  buildTanRequest,
  buildFormaliserenRequest,
  buildAnnulerenRequest,
} from "./soap/builder"
import { transformBedrijfspercelenToGeoJSON } from "./transformers/bedrijfspercelen"
import {
  transformMuterenResponse,
  transformProcesVoortgangResponse,
  transformValidatieResultaatResponse,
  transformTanResponse,
  transformTransactionResponse,
} from "./transformers/mutation"

// Default Endpoints for different environments
const ENDPOINTS = {
  acceptance: {
    tvsAuthorize: "https://pp2.toegang.overheid.nl/kvo/authorize",
    tvsToken: "https://pp2.toegang.overheid.nl/kvo/token",
    ediCropTvs: "https://edicrop-acc.agro.nl/edicrop/EdiCrop-WebService/v2",
    ediCropAba: "https://edicrop-acc.agro.nl/edicrop/EdiCropService",
  },
  production: {
    tvsAuthorize: "https://toegang.overheid.nl/kvo/authorize",
    tvsToken: "https://toegang.overheid.nl/kvo/token",
    ediCropTvs: "https://edicrop.agro.nl/edicrop/EdiCrop-WebService/v2",
    ediCropAba: "https://edicrop.agro.nl/edicrop/EdiCropService",
  },
}

// Scopes for eHerkenning (URNs) based on environment
const EHERKENNING_SCOPES = {
  acceptance: "urn:nl-eid-gdi:1.0:ServiceUUID:44345953-4138-4f53-3454-593459414d45",
  production: "urn:nl-eid-gdi:1.0:ServiceUUID:37534755-4536-4152-5747-595850325434",
}

/**
 * RVO Service types supported by the client.
 * - `'opvragenBedrijfspercelen'`: Retrieve crop fields (EDI-Crop).
 * - `'muterenBedrijfspercelen'`: Mutate/Update crop fields.
 */
export type RvoService = "opvragenBedrijfspercelen" | "muterenBedrijfspercelen"

const SERVICE_SCOPES: Record<RvoService, string> = {
  opvragenBedrijfspercelen: "RVO-WS.GEO.bp.lezen",
  muterenBedrijfspercelen: "RVO-WS.GEO.bp.muteren",
}

/**
 * Options for generating the Authorization URL.
 */
export interface AuthUrlOptions {
  /**
   * The service you want to access.
   * This determines the scope requested from eHerkenning.
   * @default 'opvragenBedrijfspercelen'
   */
  service?: RvoService
  /**
   * A unique string value used to prevent CSRF attacks.
   * If not provided, a random UUID will be generated by the `TvsAuth` class.
   * It is highly recommended to provide your own verifiable state.
   */
  state?: string
}

/**
 * The main client for interacting with RVO webservices.
 * Handles authentication (ABA or TVS/eHerkenning) and SOAP request execution.
 */
export class RvoClient {
  /** Internal configuration object. */
  private readonly config: RvoClientConfig
  /** TVS authentication handler (initialized if authMode is 'TVS'). */
  private readonly tvsAuth?: TvsAuth
  /** Current OAuth 2.0 access token. */
  private accessToken?: string

  /**
   * Creates a new instance of the RvoClient.
   *
   * @param config - Configuration options including credentials and environment.
   */
  constructor(config: RvoClientConfig) {
    this.config = {
      authMode: "TVS", // Default authentication mode
      environment: "acceptance", // Default environment
      ...config,
    }

    if (this.config.requestTimeoutMs !== undefined && this.config.requestTimeoutMs < 0) {
      throw new Error("requestTimeoutMs must be a non-negative number.")
    }

    const env = this.config.environment!
    const envEndpoints = ENDPOINTS[env]

    // Override with explicit endpoints if provided in config
    const ediCropTvsUrl = this.config.ediCropUrl || envEndpoints.ediCropTvs
    const ediCropAbaUrl = this.config.ediCropAbaUrl || envEndpoints.ediCropAba

    // Configure TVS Auth
    if (this.config.authMode === "TVS") {
      if (!this.config.tvs) {
        throw new Error("TVS authentication mode selected but TVS configuration is missing.")
      }
      const tvsAuthConf: RvoAuthTvsConfig = {
        ...this.config.tvs, // user config first
        authorizeEndpoint: this.config.tvs.authorizeEndpoint || envEndpoints.tvsAuthorize,
        tokenEndpoint: this.config.tvs.tokenEndpoint || envEndpoints.tvsToken,
      }
      this.tvsAuth = new TvsAuth(tvsAuthConf, this.config.requestTimeoutMs)
    }

    // Update config with resolved URLs for internal use
    this.config.ediCropUrl = ediCropTvsUrl
    this.config.ediCropAbaUrl = ediCropAbaUrl
  }

  // --- Auth Methods (TVS) ---

  /**
   * Generates the authorization URL for the specified RVO service (TVS/eHerkenning only).
   * Redirect the user to this URL to start the login process.
   *
   * @param options Options for generating the URL, including the target service and state.
   * @returns The fully constructed authorization URL.
   * @throws Error if authentication mode is not 'TVS'.
   */
  public getAuthorizationUrl(options: AuthUrlOptions = {}): string {
    if (this.config.authMode !== "TVS" || !this.tvsAuth) {
      throw new Error("Authentication mode is not TVS or TVS configuration is missing.")
    }

    const service = options.service || "opvragenBedrijfspercelen"
    const env = this.config.environment || "acceptance"
    const eherkenningScope = EHERKENNING_SCOPES[env]
    const serviceScope = SERVICE_SCOPES[service]

    // Combine scopes separated by space
    const fullScope = `${serviceScope} ${eherkenningScope}`

    return this.tvsAuth.getAuthorizationUrl(fullScope, options.state)
  }

  /**
   * Exchanges the authorization code received from the RVO redirect for an access token.
   * (TVS/eHerkenning only).
   *
   * @param code The authorization code from the query parameters of the redirect URI.
   * @returns A promise resolving to the token response (containing `access_token`, `expires_in`, etc.).
   * @throws Error if authentication mode is not 'TVS' or if the token exchange fails.
   */
  public async exchangeAuthCode(code: string): Promise<RvoTokenResponse> {
    if (this.config.authMode !== "TVS" || !this.tvsAuth) {
      throw new Error("Authentication mode is not TVS or TVS configuration is missing.")
    }
    const tokenData = await this.tvsAuth.getAccessToken(code)
    this.accessToken = tokenData.access_token
    return tokenData
  }

  /**
   * Manually sets the OAuth 2.0 access token.
   * Useful if you handle token storage/refreshing external to this class instance.
   *
   * @param token The access token string.
   */
  public setAccessToken(token: string) {
    this.accessToken = token
  }

  // --- Helper: Execute Request ---

  private async executeSoapRequest(soapXml: string): Promise<any> {
    const isTvs = this.config.authMode === "TVS"

    if (isTvs && !this.accessToken) {
      throw new Error(
        "Access token is missing. Authenticate via TVS first or set the access token.",
      )
    }
    if (!isTvs && (!this.config.aba?.username || !this.config.aba?.password)) {
      throw new Error("ABA authentication mode selected but ABA username or password is missing.")
    }

    const url = isTvs ? this.config.ediCropUrl! : this.config.ediCropAbaUrl!
    const headers: Record<string, string> = {
      "Content-Type": "text/xml; charset=utf-8",
    }

    if (isTvs && this.accessToken) {
      headers["Authorization"] = `Bearer ${this.accessToken}`
    }

    const controller = new AbortController()
    const timeout = this.config.requestTimeoutMs ?? 30000
    let timeoutId: NodeJS.Timeout | undefined

    if (timeout > 0) {
      timeoutId = setTimeout(() => controller.abort(), timeout)
    }

    let response: Response
    try {
      response = await fetch(url, {
        method: "POST",
        headers,
        body: soapXml,
        signal: controller.signal,
      })
    } catch (error: any) {
      if (error.name === "AbortError") {
        throw new Error(`Request to RVO service timed out after ${timeout}ms`)
      }
      throw error
    } finally {
      if (timeoutId) {
        clearTimeout(timeoutId)
      }
    }

    const responseText = await response.text()

    if (!response.ok) {
      throw new Error(`Request failed: ${response.status} - ${responseText}`)
    }

    const parser = new xml2js.Parser({
      explicitArray: false,
      tagNameProcessors: [xml2js.processors.stripPrefix],
    })
    return await parser.parseStringPromise(responseText)
  }

  // --- Service Methods ---

  /**
   * Calls the `OpvragenBedrijfspercelen` (GetCropFields) SOAP service.
   * Retrieves registered crop fields for a farm.
   *
   * @param options Optional parameters for the request (farm ID, date range).
   * @returns A promise resolving to the parsed XML response from RVO.
   * @throws Error if authentication fails or the SOAP request returns an error.
   */
  public async opvragenBedrijfspercelen(
    options: BedrijfspercelenOptions = {},
  ): Promise<BedrijfspercelenResponse> {
    const isTvs = this.config.authMode === "TVS"

    const soapXml = buildBedrijfspercelenRequest({
      farmId: options.farmId,
      periodBeginDate: options.periodBeginDate,
      periodEndDate: options.periodEndDate,
      abaCredentials: isTvs ? undefined : this.config.aba,
      issuerId: this.config.clientName,
      senderId: this.config.clientName,
    })

    const result = await this.executeSoapRequest(soapXml)

    if (options.outputFormat === "geojson") {
      return transformBedrijfspercelenToGeoJSON(result)
    }

    return result
  }

  /**
   * Submits a mutation request for crop fields.
   *
   * This is the first step in the mutation flow. It sends the proposed changes to RVO.
   * RVO returns a `TicketId` which is used to track the progress of the validation.
   *
   * @param options The mutation options, including farm ID and the list of mutations (Insert/Update/Delete).
   * @returns A promise resolving to the `TicketId`.
   */
  public async muterenBedrijfspercelen(options: MuterenRequestOptions): Promise<MuterenResponse> {
    const isTvs = this.config.authMode === "TVS"
    const soapXml = buildMuterenRequest({
      ...options,
      abaCredentials: isTvs ? undefined : this.config.aba,
      issuerId: this.config.clientName,
      senderId: this.config.clientName,
    })

    const result = await this.executeSoapRequest(soapXml)
    return transformMuterenResponse(result)
  }

  /**
   * Checks the status of a submitted mutation ticket.
   *
   * Poll this endpoint periodically after submitting a mutation until the status indicates completion
   * (e.g., status code 'GEVALIDEERD').
   *
   * @param ticketId The Ticket Id received from `muterenBedrijfspercelen`.
   * @param farmId The Farm ID (optional, but recommended if known).
   * @returns The current status and progress percentage.
   */
  public async opvragenProcesvoortgang(
    ticketId: string,
    farmId?: string,
  ): Promise<ProcesVoortgangResponse> {
    const isTvs = this.config.authMode === "TVS"
    const soapXml = buildProcesVoortgangRequest(
      ticketId,
      this.config.clientName,
      isTvs ? undefined : this.config.aba,
      farmId,
    )

    const result = await this.executeSoapRequest(soapXml)
    return transformProcesVoortgangResponse(result)
  }

  /**
   * Retrieves the validation results for a processed ticket.
   *
   * Once `opvragenProcesvoortgang` is complete, call this to see if there are any errors or warnings.
   * If validation is successful, you can proceed to formalize (commit) the changes.
   *
   * @param ticketId The Ticket Id.
   * @param farmId The Farm ID (optional).
   * @returns The validation messages (errors/warnings) and the RVO-proposed resulting fields.
   */
  public async opvragenValidatieresultaat(
    ticketId: string,
    farmId?: string,
  ): Promise<ValidatieResultaatResponse> {
    const isTvs = this.config.authMode === "TVS"
    const soapXml = buildValidatieResultaatRequest(
      ticketId,
      this.config.clientName,
      isTvs ? undefined : this.config.aba,
      farmId,
    )

    const result = await this.executeSoapRequest(soapXml)
    return transformValidatieResultaatResponse(result)
  }

  /**
   * Retrieves a TAN sequence number required for formalizing a request.
   *
   * This corresponds to requesting a TAN code via SMS (if configured) or just getting the sequence number
   * for which the user must provide the code.
   *
   * @returns The sequence number.
   */
  public async ophalenTanVolgnummer(): Promise<TanResponse> {
    const isTvs = this.config.authMode === "TVS"
    const soapXml = buildTanRequest(this.config.clientName, isTvs ? undefined : this.config.aba)

    const result = await this.executeSoapRequest(soapXml)
    return transformTanResponse(result)
  }

  /**
   * Finalizes (commits) a valid mutation request.
   *
   * This step makes the changes permanent in the RVO registry. It requires a valid TAN code
   * corresponding to the sequence number retrieved earlier.
   *
   * @param ticketId The Ticket Id of the valid request.
   * @param sequenceNumber The sequence number from `ophalenTanVolgnummer`.
   * @param tanCode The TAN code provided by the user.
   * @returns The result of the transaction (success/failure).
   */
  public async formaliserenOpgave(
    ticketId: string,
    sequenceNumber: number,
    tanCode: string,
  ): Promise<TransactionResponse> {
    const isTvs = this.config.authMode === "TVS"
    const soapXml = buildFormaliserenRequest(
      ticketId,
      sequenceNumber,
      tanCode,
      this.config.clientName,
      isTvs ? undefined : this.config.aba,
    )

    const result = await this.executeSoapRequest(soapXml)
    return transformTransactionResponse(result)
  }

  /**
   * Cancels a pending mutation request.
   *
   * Use this if the user decides not to proceed after seeing validation results,
   * or if the request is stuck/erroneous.
   *
   * @param ticketId The Ticket Id to cancel.
   * @param farmId The Farm ID (optional).
   * @returns The result of the cancellation.
   */
  public async annulerenOpgave(ticketId: string, farmId?: string): Promise<TransactionResponse> {
    const isTvs = this.config.authMode === "TVS"
    const soapXml = buildAnnulerenRequest(
      ticketId,
      this.config.clientName,
      isTvs ? undefined : this.config.aba,
      farmId,
    )

    const result = await this.executeSoapRequest(soapXml)
    return transformTransactionResponse(result)
  }
}