name: Publish to npm

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      ref:
        description: "Tag or branch to publish"
        required: true
        default: "main"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # For pnpm/action-setup to create a cache
      id-token: write # Required for trusted publishing
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"

      - name: Set up pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320
        with:
          version: 11
          run_install: true

      - name: Build project
        run: pnpm run build

      - name: Publish to npm
        run: pnpm publish --no-git-checks --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}